config/routes.rb
Taxidispatch::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations",
                                       :sessions => "sessions",
                                       :passwords => "passwords"} do

  end

  resource :user, only: [:show] do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end

  resources :my_accounts
  resources :rides
  resources :bookings
  resources :vehicle_preferences
  resource :user, only: [:show] do
    collection do
      patch 'update_password'
      get 'edit_password'

    end
  end

  get "get_address" => 'bookings#get_address'
  get "show_new_booking_map" => 'bookings#show_new_booking_map'
  get "booking_history" => 'bookings#booking_history'
  get "past_rides" => 'rides#past_rides'
  get "cancelled_rides" => 'rides#cancelled_rides'

  get "home/index"
  get "home/help"
  get "home/email_us"
  post "home/nearest_texi"
  

   root 'home#index'

  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :users
  has_many :vehicle_preferences
  has_many :pickup_addresses
  has_many :dropoff_addresses
  belongs_to :texi_infos
  
  attr_accessible :via_address, :number_of_bags, :number_of_passengers, :booked_hours, :flight_info, :recurrent_type, :pickup_datetime, :passenger_name, :passenger_phone_no, :passenger_email, :return_pickup_datetime, :pickup_time, :dropoff_time, :vehicle_preferences_attributes,:pickup_addresses_attributes, :dropoff_addresses_attributes, :user_id, :taxi_info_id

  accepts_nested_attributes_for :vehicle_preferences, :pickup_addresses, :dropoff_addresses
  
  
  def self.per_page
    10
  end
  
  # accessing pickup_address on booking_history
  def showpickup_address(booking_id)
    pa = PickupAddress.where(:booking_id => booking_id).last
    pa.address rescue ""
  end 
  
  # accessing dropoff_address on booking_history
  def showdropoff_address(booking_id)
    pa = DropoffAddress.where(:booking_id => booking_id).last
    pa.address rescue ""
  end
  
  # calculate distance between pickup and dropoff address
  def calculate_distance(booking_id)
    pa = PickupAddress.where(:booking_id => booking_id).last
    da = DropoffAddress.where(:booking_id => booking_id).last
    @loc_distance = Geocoder::Calculations.distance_between(pa.address, da.address, :units=> :km).round(1)
  end
  
  # accessing taxi_driver_name 
  def taxi_driver(taxi_info_id)
    @texi_info = TexiInfo.where(:id => taxi_info_id).first
    @texi_info.driver_name rescue ""
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	before_filter :authenticate_user!

	def index
	end
  
  # show all the bookings on booking_history
	def booking_history
    @bookings = Booking.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => 10)
	end

  def new
    @booking = Booking.new
    @pickup_address = @booking.pickup_addresses.build
    @dropoff_address = @booking.dropoff_addresses.build
    @vehicle_preference = @booking.vehicle_preferences.build
  end

  def create
    params_book = booking_params
    if !params[:booking][:taxi_info_id].blank?
      @booking = Booking.create(params_book)
      @booking.save
      redirect_to new_booking_path, notice: "Yap! Your Booking is done."
    else
      redirect_to new_booking_path, notice: "Oops!, currently taxi is not avalable."
    end
  end

  def edit
    @booking = Booking.where(:user_id => current_user.id).where('pickup_time <= ? AND dropoff_time >= ?', Time.now,  Time.now).where(:pickup_datetime => Time.now.to_date).order('pickup_datetime ASC').first rescue 0
    @booking = Booking.find(params[:id])
    render :layout => false
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update_attributes(params[:booking])
      redirect_to rides_path, notice: "Your current ride info updated successfully."
    else
      redirect_to rides_path, error: "Oops, something went wrong. Please try again"
    end
  end
  
  # allocate taxi within range for booking
  def booking_texi(vehicle_type_id, pickup_date, pickup_time, dropoff_date, dropoff_time, pickup_addr)
    @texi_info = TexiInfo.near(pickup_addr,4).where(vehicle_type_id: vehicle_type_id).map(&:id).uniq rescue 0
    @bookings = Booking.where(:user_id => current_user.id).where('pickup_time <= ? AND dropoff_time >= ?', pickup_time,  dropoff_time).where(:pickup_datetime => pickup_date.to_date).where(:return_pickup_datetime => dropoff_date.to_date).order('pickup_datetime ASC') rescue 0
    @ids = @bookings.map(&:taxi_info_id).uniq unless @bookings.blank? rescue 0
    if !@ids.blank?
      @texi_info = @texi_info-@ids
    end
    if @texi_info.blank?
      return []
    else
      return @texi_info.sample
    end
  end
  
  # show pick_up and drop_off address on new booking map
  def show_new_booking_map
    @pickup_address = Geocoder.search(params[:pick_up_addr]).first
    @dropoff_address = Geocoder.search(params[:drop_off_addr]).first
  	@hash = Gmaps4rails.build_markers(@pickup_address) do |user, marker|
		  marker.lat user.latitude
		  marker.lng user.longitude
		  marker.infowindow "PickUp Addr: "+params[:pick_up_addr]
		  marker.picture({
		  	"url" => "/assets/img/ico/map/ico_location_mark_a.png",
        "width" =>  36,
        "height" => 36
		  	})
		end
  	@hash1 = Gmaps4rails.build_markers(@dropoff_address) do |user, marker|
		  marker.lat user.latitude
		  marker.lng user.longitude
		  marker.infowindow "DropOff Addr: "+params[:drop_off_addr]
		  marker.picture({
		  	"url" => "/assets/img/ico/map/ico_location_mark_b.png",
        "width" =>  36,
        "height" => 36
		  	})
		end

    @loc_distance = Geocoder::Calculations.distance_between(params[:pick_up_addr], params[:drop_off_addr], :units=> :km).round(1)
    respond_to do |format|
      format.js
    end
  end
  
  # recurrent pick_up and drop_off address 
  def get_address
    booking = Booking.where(user_id: current_user.id).last
    pick_up_addr = PickupAddress.where(:booking_id => booking.id).last
    drop_off_addr = DropoffAddress.where(:booking_id => booking.id).last
    hash = {:pick_up_addr => pick_up_addr.address, :drop_off_addr => drop_off_addr.address}
    respond_to do |format|
      format.json { render :json => hash.to_json, :status => 200 }
    end
  end

  private
  # handling booking parameters of booking tab
  def booking_params
    params[:booking][:user_id] = current_user.id
    vehicle_type_id = params[:booking][:vehicle_preferences_attributes].first[1][:vehicle_type_id]
    pickup_date = params[:booking][:pickup_datetime]
    pickup_time = params[:booking][:pickup_time]
    dropoff_date = params[:booking][:return_pickup_datetime]
    dropoff_time = params[:booking][:dropoff_time]
    pickup_addr = params[:booking][:pickup_addresses_attributes].first[1][:address]
    params[:booking][:taxi_info_id] = booking_texi(vehicle_type_id, pickup_date, pickup_time, dropoff_date, dropoff_time, pickup_addr)
    params.require(:booking).permit(:dropoff_address, :via_address, :number_of_bags, :number_of_passengers, :booked_hours, :flight_info, :recurrent_type,:passenger_name, :passenger_phone_no, :passenger_email, :pickup_datetime, :return_pickup_datetime, :pickup_time, :dropoff_time, :user_id, :taxi_info_id, :vehicle_preferences_attributes => [:number_of_vehicle, :booking_id, :vehicle_type_id], :pickup_addresses_attributes => [:address, :booking_id], :dropoff_addresses_attributes => [:address, :booking_id])
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
	def get_tab_status(action, tab_string)
    case tab_string
      when 'index'
        return 'active' if ['index'].include?(action)
      when 'new'
        return 'active' if ['new'].include?(action)
      when 'booking_history'
        return 'active' if ['booking_history'].include?(action)
    end
  end

  def get_tabs_partial(action)
    case action
      when 'index'
        'booking_tab'
      when 'new'
        'booking_tab'
      when 'booking_history'
        'booking_history'
    end
  end

  def get_booking_partial(action)
    case action
      when 'index'
        "bookings/booking_tab"
      when 'new'
        "bookings/booking_tab"
      when 'booking_history'
        "bookings/booking_history"
    end
  end
  
  # parse pickup_date
  def booking_pickup_date(date)
    date.strftime("%d %b %Y") rescue 0
  end
  
  # parse pickup_time 
  def booking_pickup_time(time)
    time.strftime("%H:%M") rescue 0
  end
  
  # show rides status on booking_history
  def show_status(pickup_date,pickup_time,dropoff_date,dropoff_time)
    status = ""
    if pickup_date == Time.now.to_date && pickup_time <= Time.now && dropoff_date >= pickup_date
      status = "current"
    elsif pickup_date > Time.now.to_date && dropoff_date >= pickup_date
      status = "schedule"
    else
      status = "past"  
    end
  end
end

app/views/bookings/_booking_history.html.erb
<div class="content_wrap clearfix">
	<div class="content booking_history gray_box clearfix">
    <%= form_tag booking_history_path, :method => "get" do %>  
    <div class="table_filters">
      <ul class="form_wrap clearfix">
        <li class="fl-l"><%= text_field_tag :pickup_address, params[:pickup_address], :placeholder => 'filter by address', :class => "input_ico input_ico_search" %></li>
        <li class="fl-l"><%= text_field_tag :pickup_datetime, params[:pickup_datetime], :placeholder => 'filter by date', :class => "input_ico input_ico_search" %></li>
        <li class="fl-l"><%= text_field_tag :pickup_time, params[:pickup_time], :placeholder => 'filter by time', :class => "input_ico input_ico_time pickup_time timespinner" %></li>
      </ul>
    </div>
    <% end %>
    <table id="booking_history" class="display">
      <thead>
        <tr>
          <th>Date</th>
          <th>Pickup &amp; Drop Off</th>
          <th>Distance</th>
          <th>Payment</th>
          <th>Passenger</th>
          <th>Driver</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking|%>
        <tr>
          <td><%= booking_pickup_date(booking.try(:pickup_datetime))%>, <%= booking_pickup_time(booking.try(:pickup_time))%></td>
          <td><%= booking.showpickup_address(booking.id) rescue ""%> & <%= booking.showdropoff_address(booking.id) %></td>
          <td><%= booking.calculate_distance(booking.id) rescue ""%> km</td>
          <td>€ <%= booking.calculate_distance(booking.id)*2 rescue 0 %></td>
          <td><%= booking.passenger_name %></td>
          <td><%= booking.taxi_driver(booking.taxi_info_id) %></td>
          <td><%= show_status(booking.try(:pickup_datetime), booking.try(:pickup_time), booking.try(:return_pickup_datetime), booking.try(:dropoff_time)) rescue 0 %></td>
        </tr>
        <% end %>
      </tbody>
    </table>  
  </div>
  <div class="pagination fl-r clearfix">
    <div class="fl-l">
      <%= will_paginate @bookings, :class=>"paging_full_numbers"%>
    </div>
  </div> 
  <%= link_to "Create a New Booking", new_booking_path, :class => "btn btn_orange"  %>
</div>

            
       

app/views/bookings/_booking_main_tab.html.erb
<div class="content_wrap clearfix">
  <div class="content_heading">
    New Booking
  </div>

  <div class="content_nav dblshadow">
    <ul>
      <li class="first <%= get_tab_status(params[:action], 'new') %>">
        <%= link_to new_booking_path do %>
          New Booking<span class="content_nav_arrow"></span>
        <% end %>
      </li>
      <li class="last <%= get_tab_status(params[:action], 'booking_history') %>">
        <%= link_to booking_history_path do %>
          Booking History<span class="content_nav_arrow"></span>
        <% end %>
      </li>
    </ul>
  </div>
  <%= render :partial => get_tabs_partial(params[:action])%>
</div>

app/views/bookings/_booking_tab.html.erb
<%= render :partial => "layouts/masseges"%>
<div class="content new_booking gray_box clearfix">
 	<table>
		<tr>
			<th class="col1" valign="top"> 
        <h1>Passenger / Account</h1>
        <span class="btn_round">?</span>
      </th>
      <th class="col2" valign="top">
        <a href="#" class="btn btn_gray btn_ico"><span class="ico ico_location"></span>Show Suggested Locations</a>
      </th>
      <th class="col3" valign="top">
        <h1>Payment</h1>
        <span class="btn_round">?</span>
      </th>
  	</tr>
    <%= form_for @booking do |f| %>
     	<tr>
     		<td class="col1" valign="top">
           <hr>
          <div class="new_booking_item new_booking_account">
            <ul class="form_wrap clearfix">
              <li><%= f.text_field :passenger_name, :value => "#{current_user.first_name} #{current_user.last_name}"%></li>
               <li>
                <ul>
                  <li><%= f.text_field :passenger_phone_no, :value => "#{current_user.phone_no}"%></li>
                  <li><%= f.text_field :passenger_email, :value => "#{current_user.email}"%></li>
                </ul>
              </li>
              <li>
                <input type="radio" id="main_account_contact" name="account_contact" checked="checked" class="custom_radio"><label for="main_account_contact" class="radiobutton">Main Account Contact</label>
                <a id="show_minor_contact" href="#" class="btn btn_orange btn_add fl-r">+</a>
              </li>
            </ul>
            <ul id="minor_contact" class="form_wrap clearfix disp-n">
              <li><input type="text" value="Benjamin Westrup"></li>
              <li>
                <ul>
                  <li><input type="text" value="+447985364480"></li>
                  <li><input type="text" value="Email Address"></li>
                </ul>
              </li>
              <li>
                <input type="radio" id="minor_account_contact" name="account_contact" class="custom_radio"><label for="minor_account_contact" class="radiobutton">Main Account Contact</label>
                <a href="#" class="btn btn_orange btn_add fl-r">+</a>
              </li>
            </ul>
          </div>

          <hr>
          <div class="new_booking_item new_booking_booking">
            <h1>Booking</h1>
            <span class="btn_round">?</span>
            <ul class="form_wrap clearfix">
              <li class="clearfix">
                <span>Pick Up:</span>
                <%= f.fields_for :pickup_addresses do |pa|%>
                  <%= pa.text_field :address, :value => "#{params[:pickup_nearest_texi]}" %>
                  <a id="show_add_via" href="#" class="addvia fl-r">Add Via</a>
                <%end%>
              </li>
              <li id="add_via"class="disp-n">
                <span>Via:</span>
                <%= f.text_field :via_address %>
              </li>
              <li>
                <span>Drop Off:</span>
                <%= f.fields_for :dropoff_addresses do |da|%>
                  <%= da.text_field :address %>
                <%end%>
              </li>
              <li>
                <ul>
                  <li><%= f.text_field :pickup_datetime, :class =>"input_ico input_ico_date datepicker", :placeholder => "Pickup Date"%></li>
                  <li><%= text_field_tag 'pickup_time1', nil,:class =>"input_ico input_ico_time timespinner",:id => "pickup_time"%></li>
                  <li><%= f.hidden_field :pickup_time ,:id => "pickup_time_id"%></li>
                </ul>
              </li>
              <li>
                <ul>
                  <li><%= f.text_field :return_pickup_datetime, :class=>"input_ico input_ico_date datepicker", :placeholder =>"Return Pickup Date"%></li>
                  <li><%= text_field_tag 'dropoff_time', nil , :class=>"input_ico input_ico_time timespinner", :id => "dropoff_time"%></li>
                  <li><%= f.hidden_field :dropoff_time ,:id => "dropoff_time_id"%></li>
                </ul>
              </li>
              <li>
                <ul>
                  <li><%= text_field_tag 'number_of_bags', nil , :placeholder=> "Bags",:class=>"number spinner", :id => "number_of_bags" %></li>
                  <li><%= f.hidden_field :number_of_bags ,:id => "number_of_bags_id"%></li>
                  <li><%= text_field_tag :number_of_passengers1, nil , :placeholder=> "Passengers", :class=>"number spinner", :id => "number_of_passengers"  %></li>
                  <li><%= f.hidden_field :number_of_passengers ,:id => "number_of_passengers_id"%></li>
                </ul>
              </li>
            </ul>
          </div>

          <hr>
          <div class="new_booking_item">
            <h1>Hours Booked</h1>
            <ul class="form_wrap clearfix">
              <li><%= f.text_field :booked_hours, :placeholder=>"Enter the number of hours required if known"%></li>
            </ul>
          </div>

          <hr>
          <div class="new_booking_item">
            <h1>Flight Info</h1>
            <ul class="form_wrap clearfix">
              <li><%= f.text_field :flight_info, :placeholder=>"If flying, enter your flight info"%></li>
            </ul>
          </div>
          </td>
          <td class="col2"  valign="top">
          <hr>
          <%= f.fields_for :vehicle_preferences do |vp| %>
            <div class="new_booking_item new_booking_vehicle">
              <h1>Vehicle Preferences</h1>
              <span class="btn_round">?</span>
              <ul class="form_wrap clearfix">
                <li class="fl-l">
                  <%= vp.select(:vehicle_type_id, VehicleType.all.collect {|p| [ p.vehicle_type, p.id ] }, {}, {:class => "type select_menu"}) %>
                </li>
                <li class="fl-l">
                <%= text_field_tag 'number_of_vehicle1', nil , :placeholder=>"Number",:class=>"number spinner",:id => "number_of_vehicle"%>
                <%= vp.hidden_field :number_of_vehicle ,:id => "number_of_vehicle_id"%>
                </li>
                <li class="fl-r">
                  <a id="show_another_vehicle" href="#" class="btn btn_orange btn_add">+</a>
                </li>
              </ul>
              <ul id="another_vehicle" class="form_wrap clearfix disp-n">
                <li class="fl-l">
                  <%= vp.select(:vehicle_type_id, {}, {:class => "type select_menu"}) %>
                </li>
                <li class="fl-l">
                  <%= text_field_tag 'number_of_vehicle1', nil , :placeholder=>"Number",:class=>"number spinner",:id => "number_of_vehicle1"%>

                </li>
              </ul>
            </div>
          <% end %>

          <hr>
          <div class="new_booking_fieldset new_booking_extras clearfix">
            <h1>Extras</h1>
            <span class="btn_round">?</span>
            <ul class="form_wrap first fl-l clearfix">
              <li>
              	<input id="airport_pickup" type="checkbox" class="custom_checkbox"><label for="airport_pickup" class="checkbox">Airport Pickup</label>
              </li>
              <li>
              	<input id="battery_boosts" type="checkbox" class="custom_checkbox"><label for="battery_boosts" class="checkbox">Battery Boosts</label>
              </li>
              <li>
                <input id="medical_visit" type="checkbox" class="custom_checkbox"><label for="medical_visit" class="checkbox">Medical Visit</label>
              </li>
              <li>
              	<input id="baby_scooter" type="checkbox" class="custom_checkbox"><label for="baby_scooter" class="checkbox">Baby Scooter</label>
              </li>
              <li>
              	<input id="baby_pram" type="checkbox" class="custom_checkbox"><label for="baby_pram" class="checkbox">Baby Pram</label>
              </li>
              <li>
              	<input id="wheelchair" type="checkbox" class="custom_checkbox"><label for="wheelchair" class="checkbox">Wheelchair</label>
              </li>    
            </ul>
            <ul class="form_wrap fl-l clearfix">
            	<li>
              	<input id="rush_parcel" type="checkbox" class="custom_checkbox"><label for="rush_parcel" class="checkbox">Rush Parcel Delivery</label>
              </li>
              <li>
              	<input id="event_transportation" type="checkbox" class="custom_checkbox"><label for="event_transportation" class="checkbox">Event Transportation</label>
              </li>
              <li>
              	<input id="luggage" type="checkbox" class="custom_checkbox"><label for="luggage" class="checkbox">Help with Luggage</label>
              </li>
              <li>
                <input id="oversized" type="checkbox" class="custom_checkbox"><label for="oversized" class="checkbox">Oversized Luggage</label>
              </li>
              <li>
              	<input id="multilingual" type="checkbox" class="custom_checkbox"><label for="multilingual" class="checkbox">Multi-Lingual Driver</label>
              </li>    
            </ul>
          </div>

          <hr>
          <div class="new_booking_fieldset new_booking_accessability clearfix">
            <h1>Accessability</h1>
            <span class="btn_round">?</span>
            <ul class="form_wrap first fl-l clearfix">
              <li>
                <input id="access_wheelchair" type="checkbox" class="custom_checkbox"><label for="access_wheelchair" class="checkbox">Wheelchair</label>
              </li>
              <li>
                <input id="carset" type="checkbox" class="custom_checkbox"><label for="carset" class="checkbox">Carseat</label>
              </li>    
            </ul>
            <ul class="form_wrap fl-l clearfix">
            	<li>
              	<input id="guide_dob" type="checkbox" class="custom_checkbox"><label for="guide_dob" class="checkbox">Guide Dob</label>
              </li>
              <li>
              	<input id="infant" type="checkbox" class="custom_checkbox"><label for="infant" class="checkbox">Infant</label>
              </li> 
            </ul>
          </div>

          <hr>
          <div class="new_booking_item new_booking_recurrent">
            <h1>Recurrent</h1>
            <span class="btn_round">?</span>
            <ul class="form_wrap clearfix">
              <li>
                <input type="radio" id="single_taxi" name="recurrent" checked="checked" class=""><label class="radiobutton" for="single_taxi">Single Taxi Service</label>
              </li>
              <li>
                <input type="radio" id="recurrent_taxi" name="recurrent" class=""><label for="recurrent_taxi" class="radiobutton">Recurrent Taxi Service Needed</label>
              </li>
            </ul>
          </div>
        </td>
        <td class="col3"  valign="top">
          <hr>
          <div class="new_booking_item new_booking_payment">
            <input type="radio" id="cash" name="payment" checked="checked" class="custom_radio"><label for="cash" class="radiobutton">Cash</label>
            <input type="radio" id="debit_card" name="payment" class="custom_radio"><label for="debit_card" class="radiobutton">Debit Card</label>
            <input type="radio" id="credit_card" name="payment" class="custom_radio"><label for="credit_card" class="radiobutton no-mrg">Credit Card</label>
            <div class="summary">
              <p><span>Account:</span>Benjamin Westrup</p>
              <p><span>Jouney: </span>1hr 49min</p>
              <p><span>Distance:</span>130.9km</p>
              <p><span>Fare:</span>€654.70</p>
              <p class="total"><span>TOTAL:</span>€654.70</p>
            </div>
            <%= button_tag(:class => 'btn btn_orange', :id =>"book_now") do %>
              Book Now
            <%end%>
          </div>

  	 		  <div class="new_booking_item new_booking_map" id="new_booking_map_id">
  				  <h1>Map</h1>
            <%= render :partial => "new_booking_map" %>
  				</div>
    		</td>
     	</tr>
    <% end %>
   </table>
 </div>
<script type="text/javascript">
  $(document).ready(function() {
    $("#book_now").click(function() {
      $('#pickup_time_id').val($('#pickup_time').val());
      $('#dropoff_time_id').val($('#dropoff_time').val());
      $('#number_of_bags_id').val($('#number_of_bags').val());
      $('#number_of_passengers_id').val($('#number_of_passengers').val());
      $('#number_of_vehicle_id').val($('#number_of_vehicle').val());
    });
  });
</script>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#booking_dropoff_addresses_attributes_0_address").change(function(event){
      var pick_up_addr = $('#booking_pickup_addresses_attributes_0_address').val();
      var drop_off_addr = $('#booking_dropoff_addresses_attributes_0_address').val();
      if (pick_up_addr != ""){
        $.ajax({
          url: "<%= show_new_booking_map_path %>",
          type: "get",
          data: {'pick_up_addr': pick_up_addr, 'drop_off_addr' :drop_off_addr},
          success: function(data){
          }
        });
      }
    });
  });
</script>
<script type="text/javascript">
  $(document).ready(function() {
    $("#recurrent_taxi").click(function() {
      $.ajax({
        url: "<%= get_address_path %>",
        type: "get",
        data: {},
        dataType: 'JSON',
        success: function(data){
          $('#booking_pickup_addresses_attributes_0_address').val(data.pick_up_addr );
          $('#booking_dropoff_addresses_attributes_0_address').val(data.drop_off_addr );
          pick_up_addr = data.pick_up_addr
          drop_off_addr = data.drop_off_addr
          if (pick_up_addr != ""){
            $.ajax({
              url: "<%= show_new_booking_map_path %>",
              type: "get",
              data: {'pick_up_addr': pick_up_addr, 'drop_off_addr' :drop_off_addr},
              success: function(data){
              }
            });
          }
        }
      });
    });
  });
</script>

app/views/bookings/_new_booking_map.html.erb
<div id="map" class="map_holder">
</div>
<em>Estimated Distance: <%= @loc_distance%>km</em>
<script>
handler = Gmaps.build('Google');
handler.buildMap({ mapTypeId: google.maps.MapTypeId.ROADMAP, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  markers = handler.addMarkers(<%=raw @hash1.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);
});
</script>

app/views/bookings/booking_history.html.erb
<%= render :partial => 'booking_main_tab' %>

app/views/bookings/edit.html.erb
<div class="modal_wrap">
  <%= form_for @booking, url: booking_path do |f| %>
    <ul class="form_wrap clearfix">
      <li>
        <span>Pick Up:</span>
        <%= f.fields_for :pickup_addresses do |pa|%>
          <%= pa.text_field :address %>
        <%end%>
      </li>
      <li>
        <span>Drop Off:</span>
        <%= f.fields_for :dropoff_addresses do |da|%>
          <%= da.text_field :address %>
        <%end%>
      </li>
      <li>
          <span>Pickup_date:</span>
          <%= f.text_field :pickup_datetime, :class =>"input_ico input_ico_date datepicker", :value => "#{edit_current_ride_pickup_date(@booking.pickup_datetime)}" %>
      </li>
      <li>
          <span>Pickup_time:</span>
          <%= f.text_field :pickup_time, :class=>"input_ico input_ico_time timespinner",  :value => "#{current_rides_pickup_time(@booking.pickup_time)}" %>
      </li>
    </ul>

    <div class="modal_twobutton">
      <%= f.submit "Save Changes", :class => "btn btn_orange" %>
      <%= f.submit "Cancel", :type=> "button", :class => "btn btn_gray_onblack" , :disable => true%>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<%= render :partial => 'booking_main_tab' %>

app/views/bookings/new.html.erb
<%= render :partial => 'booking_main_tab' %>

app/views/bookings/show_new_booking_map.js.erb
$("#new_booking_map_id").html("<%= escape_javascript(render(:partial => 'new_booking_map', :locals => { :@hash => @hash })) %>");