config/routes.rb
Taxidispatch::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations",
                                       :sessions => "sessions",
                                       :passwords => "passwords"} do

  end

  resource :user, only: [:show] do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end

  resources :my_accounts
  resources :rides
  resources :bookings
  resources :vehicle_preferences
  resource :user, only: [:show] do
    collection do
      patch 'update_password'
      get 'edit_password'

    end
  end

  get "get_address" => 'bookings#get_address'
  get "show_new_booking_map" => 'bookings#show_new_booking_map'
  get "booking_history" => 'bookings#booking_history'
  get "past_rides" => 'rides#past_rides'
  get "cancelled_rides" => 'rides#cancelled_rides'

  get "home/index"
  get "home/help"
  get "home/email_us"
  post "home/nearest_texi"
  

   root 'home#index'

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:hash] != nil
      @hash = params[:hash]
    else
    	@texi_info = TexiInfo.all
      @hash = Gmaps4rails.build_markers(@texi_info) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.picture({
          "url" => "assets/img/ico/map/ico_location_mark.png",
          "width" =>  36,
          "height" => 36
          })
      end
    end
  end
  
  def help
  end
  
  # sending email
  def email_us
    render :layout => false
  end
  
  # show nearest texi for booking on home map within range
  def nearest_texi
    if params[:pick_up_id] != nil
      @texi_info = TexiInfo.near(params[:pick_up_id],4)
    else
      @texi_info = TexiInfo.all
    end
    @hash = Gmaps4rails.build_markers(@texi_info) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow user.address
      marker.picture({
        "url" => "assets/img/ico/map/ico_location_mark.png",
        "width" =>  36,
        "height" => 36
        })
    end
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def get_home_tab_status(action, tab_string)
    case tab_string
      when 'index'
        return 'active' if ['index'].include?(action)
      when 'pickup_and_dropoff'
        return 'active' if ['pickup_and_dropoff'].include?(action)
    end
  end

  def get_home_tabs_partial(action)
    case action
      when 'index'
        'view_home_map'
      when 'pickup_and_dropoff'
        'pickup_and_dropoff'
    end
  end

  def get_home_partial(action)
    case action
      when 'index'
        "home/view_home_map"
      when 'pickup_and_dropoff'
        "home/pickup_and_dropoff"
    end
  end
end

app/views/home/_home_page_tab.html.erb
<div class="content_heading">
  Web Booking Taxi Service
</div>

<div class="content_nav dblshadow">
  <ul>
    <li class="first <%= get_home_tab_status(params[:action], 'index') %>">
      <%= link_to root_path do %>
        View Map<span class="content_nav_arrow"></span>
      <% end %>
    </li>
    <li class="last <%= get_tab_status(params[:action], 'pickup_and_dropoff') %>">
      <%= link_to '#' do %>
        Pick Up &amp; Drop Off<span class="content_nav_arrow"></span>
      <% end %>
    </li>
  </ul>
</div>
<%= render :partial => "layouts/masseges"%>
<%= render :partial => get_home_tabs_partial(params[:action])%>

app/views/home/_taxi_location_map.html.erb
<div id="map" class="map_holder"></div>

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/home/_view_home_map.html.erb
<div class="content home clearfix">
  <div class="gray_box clearfix">
    <div class="home_map fl-l" id="search_texi">
      <%= render :partial => "taxi_location_map"%>
    </div>
    <div class="home_sidebar fl-r">
      <ul class="home_sidebar_menu">
        <li><%= link_to new_booking_path do %> Bookin Information<span class="ico ico_arrow"></span><% end %></li>
        <li><a href="#">Booked<span class="ico ico_arrow"></span></a></li>
        <li><a href="#">Dispathed<span class="ico ico_arrow"></span></a></li>
        <li><a href="#">E.T.A.<span class="ico ico_arrow"></span></a></li>
      </ul>
    </div>
  </div>
  <div class="home_searchbar">
    <%= form_tag new_booking_path, :method => 'get' do %>
    <% hash = @texi_info %>
      <%= hidden_field_tag 'texi_id', '#{hash}' %>
      <ul class="form_wrap clearfix">
        <li class="fl-l"><%= text_field_tag 'pickup_nearest_texi', nil, :placeholder => "Pick Up", :class => "input_ico_right input_ico_search" %></li>
        <li class="fl-l"> <%= submit_tag "Book the Nearest Taxi", :class => "btn btn_orange" %></li>
      </ul>
    <%end%>
  </div>
</div>

<script type="text/javascript">
jQuery(document).ready(function(){
  jQuery("#pickup_nearest_texi").keypress(function(event){
    $.ajax({
      url: "<%= home_nearest_texi_path %>",
      type: "POST",
      data: 'pick_up_id='+$(this).val(),
      success: function(data){
      }
    });
  });
});
</script>

app/views/home/help.html.erb
<div class="content_wrap clearfix">

        <div class="content_heading">
            Help
        </div>  

        <div class="content help clearfix">

            <div class="help_item">
                <h2>Chater Taxi Help</h2>
                <h3>Overview</h3>
                <ol>
                    <li><a href="#">How do I book a car?</a></li>
                    <li><a href="#">Where can I book a car?</a></li>
                    <li><a href="#">What if a booking is not available in a partifular area?</a></li>
                    <li><a href="#">What happens after I book a ride?</a></li>
                    <li><a href="#">How are transportation providers chosen?</a></li>
                    <li><a href="#">How do I keep track of my rides using ride status?</a></li>
                    <li><a href="#">How do I made a change to an existing reservation, such as the pickup time or drop off time?</a></li>
                    <li><a href="#">How can another RideCharge user or Administrative Assistant book a ride for me?</a></li>
                </ol>
                <h3>Payment and E-Receipts</h3>
                <ol>
                    <li><a href="#">How do I pay for a ride?</a></li>
                    <li><a href="#">How do I get a receipt for a ride?</a></li>
                    <li><a href="#">How are tips and fees handled?</a></li>
                    <li><a href="#">What happens if I pay with cash?</a></li>
                </ol>
                <h3>Special Situations</h3>
                <ol>
                    <li><a href="#">What do I do if I can’t find my car?</a></li>
                    <li><a href="#">What do I do if I want to cancel a ride I have booked?</a></li>
                    <li><a href="#">Who do I call if there is a problem?</a></li>
                    <li><a href="#">How do airport pickups work?</a></li>
                </ol>
                <h3>Account Management</h3>
                <ol>
                    <li><a href="#">How do I change my communication preferences?</a></li>
                </ol>
            </div>

            <div class="help_item">
                <h2>Mobile Application Help</h2>
                <h3>Overview</h3>
                <ol>
                    <li><a href="#">How do I book a ride?</a></li>
                    <li><a href="#">How does the Default Provider feature work?</a></li>
                    <li><a href="#">How do I pay for a ride?</a></li>
                    <li><a href="#">How do I see rides I have taken?</a></li>
                </ol>
                <h3>Troubleshooting</h3>
                <ol>
                    <li><a href="#">What do I do if I rejected https connections on my device?</a></li>
                    <li><a href="#">How do I re-download the RideCharge mobile application?</a></li>
                    <li><a href="#">What do I do if the driver asks for a signature?</a></li>
                    <li><a href="#">Why do I get a confirmation number after my ride?</a></li>
                    <li><a href="#">How do I pay if I am using a different phone?</a></li>
                </ol>
            </div>

        </div>

        

    </div>

app/views/home/index.html.erb
<div class="content_wrap clearfix" >
  <%= render :partial => 'home_page_tab' %>
</div>

app/views/home/nearest_texi.js.erb
$("#search_texi").html("<%= escape_javascript(render(:partial => 'taxi_location_map', :locals => { :@hash => @hash })) %>");