config/routes.rb
Taxidispatch::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations",
                                       :sessions => "sessions",
                                       :passwords => "passwords"} do

  end

  resource :user, only: [:show] do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end

  resources :my_accounts
  resources :rides
  resources :bookings
  resources :vehicle_preferences
  resource :user, only: [:show] do
    collection do
      patch 'update_password'
      get 'edit_password'

    end
  end

  get "get_address" => 'bookings#get_address'
  get "show_new_booking_map" => 'bookings#show_new_booking_map'
  get "booking_history" => 'bookings#booking_history'
  get "past_rides" => 'rides#past_rides'
  get "cancelled_rides" => 'rides#cancelled_rides'

  get "home/index"
  get "home/help"
  get "home/email_us"
  post "home/nearest_texi"
  

   root 'home#index'

  

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_filter :authenticate_user!
  
  # show current_ride 
	def index
    @rides = Booking.where(:user_id => current_user.id).where('pickup_time <= ? AND dropoff_time >= ?', Time.now,  Time.now).where(:pickup_datetime => Time.now.to_date).order('pickup_datetime ASC').first rescue 0

    if @rides.blank?
      @rides = Booking.where(:user_id => current_user.id).where(:pickup_datetime => Date.today..Date.today.next_month).order('pickup_datetime ASC').first rescue 0
    end
  	@pickup_address = PickupAddress.where(:booking_id => @rides.id).first unless @rides.blank?
  	@dropoff_address = DropoffAddress.where(:booking_id => @rides.id).first unless @rides.blank?
    @texi = TexiInfo.where(:id => @rides.taxi_info_id).first rescue 0
  	@hash = Gmaps4rails.build_markers(@pickup_address) do |user, marker|
		  marker.lat user.latitude
		  marker.lng user.longitude
		  marker.infowindow "PickUp Addr: "+@pickup_address.address
		  marker.picture({
		  	"url" => "assets/img/ico/map/ico_location_mark_a.png",
        "width" =>  36,
        "height" => 36
		  	})
		end
  	@hash1 = Gmaps4rails.build_markers(@dropoff_address) do |user, marker|
		  marker.lat user.latitude
		  marker.lng user.longitude
		  marker.infowindow "DropOff Addr: "+@dropoff_address.address
		  marker.picture({
		  	"url" => "assets/img/ico/map/ico_location_mark_b.png",
        "width" =>  36,
        "height" => 36
		  	})
		end
    
    @scheduled_rides = Booking.where(:user_id => current_user.id).where(:pickup_datetime => Date.tomorrow..Date.today.next_month).order('pickup_datetime ASC') rescue 0
    

    @all_current_rides = Booking.where(:user_id => current_user.id).where(:pickup_datetime => Date.today).order('pickup_datetime ASC') rescue 0
  end
  
  # show cancel ride 
	def cancelled_rides
    @scheduled_rides = Booking.where(:user_id => current_user.id).where(:pickup_datetime => Date.tomorrow..Date.today.next_month).order('pickup_datetime ASC') rescue 0
	end
  
  # delete current_ride on rides
  def destroy
    @rides = Booking.where(:user_id => current_user.id).where(:id => params[:id]).first rescue 0
    @rides.destroy unless @rides.blank?
    redirect_to rides_path, :notice => "Your booking has been deleted"
  end
  
  # show past_ride
	def past_rides
    if (params[:pickup_datetime].to_s!= "" && params[:return_pickup_datetime].to_s!= "")
      from_date = DateTime.parse(params[:pickup_datetime]).strftime("%Y-%m-%d") 
      to_date = DateTime.parse(params[:return_pickup_datetime]).strftime("%Y-%m-%d")
      @rides = Booking.where(:user_id => current_user.id).where(:pickup_datetime => from_date..to_date).where('pickup_datetime < ?', Time.now.to_date).paginate(:page => params[:page], :per_page => 10).order('pickup_datetime ASC')
      respond_to do |format|
        format.js
      end
    else
      @rides = Booking.where(:user_id => current_user.id).where('pickup_datetime < ?', Time.now.to_date).paginate(:page => params[:page], :per_page => 10).order('pickup_datetime ASC')
    end
    @scheduled_rides = Booking.where(:user_id => current_user.id).where(:pickup_datetime => Date.tomorrow..Date.today.next_month).order('pickup_datetime ASC') rescue 0
  end
end

app/helpers/rides_helper.rb
module RidesHelper
	def get_rides_tab_status(action, tab_string)
    case tab_string
      when 'index'
        return 'active' if ['index'].include?(action)
      when 'current_rides'
        return 'active' if ['current_rides'].include?(action)
      when 'past_rides'
        return 'active' if ['past_rides'].include?(action)
      when 'cancelled_rides'
        return 'active' if ['cancelled_rides'].include?(action)
    end
  end

  def get_rides_tabs_partial(action)
    case action
      when 'index'
        'current_rides_tab'
      when 'past_rides'
        'past_rides_tab'
      when 'cancelled_rides'
        'cancelled_rides_tab'
    end
  end

  def get_rides_partial(action)
    case action
      when 'index'
        "rides/current_rides_tab"
      when 'past_rides'
        "rides/past_rides_tab"
      when 'cancelled_rides'
        "rides/cancelled_rides_tab"
    end
  end
  
  # parse current date
  def current_date
    Time.now.strftime("%b %d, %Y")
  end

  # parse past date
  def past_date(date)
    date.strftime("%b %d, %Y") rescue 0
  end
  
  def get_taxi_info(taxi_info_id)
    @texi = TexiInfo.where(:id => taxi_info_id).first
  end
  
  # parse pickup date
  def current_rides_pickup_date(date)
    date.strftime("%A, %m/%d") rescue 0
  end
  
  # parse pickup date for edit current ride
  def edit_current_ride_pickup_date(date)
    date.strftime('%d/%m/%Y') rescue 0
  end
  
  # parse pickup_time
  def current_rides_pickup_time(time)
    time.strftime("%H:%M%p") rescue 0
  end
end

app/views/rides/_cancelled_rides_tab.html.erb
<div class="content grid my_rides clearfix">
  <div class="col3 col3_span fl-l">
    <div class="grid_item current_rides gray_box">
      <div class="grid_item_headings clearfix">
        <h1 class="fl-l">Cancelled Rides</h1>
        <div class="fl-r">
          <ul class="form_wrap clearfix">
            <li class="no-mrg">
              <ul>
                <li class="fl-l no-mrg">From <input type="text" value="Start Date" class="input_ico input_ico_date datepicker"></li>
                <li class="fl-l no-mrg">&nbsp;to<input type="text" value="End Date" class="input_ico input_ico_date datepicker"></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
      <hr>
      <div class="grid_item_content">
        <p class="norides_promt">Once you cancel any rides, they will appear here. You can search for your rides by specifying dates on the calendar above.</p>
      </div>
    </div>
  </div>
  <div class="col3 sidebar fl-r">
    <div class="grid_item gray_box">
      <div class="grid_item_headings clearfix">
        <h1>Schedule Rides</h1>
      </div>
      <hr>
        <%= render :partial => 'schedule_rides' %>
    </div>
    <div class="grid_item  all_current_rides gray_box">
      <div class="grid_item_headings clearfix">
        <h1>All Cancelled Rides</h1>
      </div>
      <hr>
      <div class="grid_item_content">
        <strong>You have no Cancelled Rides</strong>
      </div>
    </div>
  </div>
</div>

app/views/rides/_current_rides_tab.html.erb
<%= render :partial => "layouts/masseges"%>
<div class="content grid my_rides clearfix">
  <div class="col3 col3_span fl-l">
    <div class="grid_item current_rides gray_box">
      <div class="grid_item_headings clearfix">
          <h1>Current Ride</h1>
      </div>
      <hr>
      <div class="grid_item_content">
        <div class="clearfix">
          <h2 class="fl-l"><%= current_rides_pickup_date(@rides.try(:pickup_datetime)) %> Taxi Ride:</h2>
          <% unless (@rides.try(:id)).blank?%>
          <%= link_to 'Cancle Ride',{:action => "destroy", :controller => "rides", :id => @rides.try(:id)},
            :confirm => 'Are you sure?', :method => :delete , :class => "btn_orange fixed_width fl-r"%>
          <% end %>
          <%= link_to "Edit Details", edit_booking_path(@rides.try(:id)), :class => "modal_ajax btn btn_orange fixed_width fl-r cboxElement", :title => "Edit Details" %>
          
        </div>
        <div class="current_rides_item">
          <h3>Taxi Company:</h3>
          <p><%= @texi.try(:taxi_company_name)%></p>
          <p><%= @texi.try(:taxi_company_phone_no)%></p>
        </div>
        <div class="clearfix">
          <div class="current_rides_item pickup fl-l">
            <h3>Pickup:</h3>
            <p><%= @pickup_address.try(:address) %></p>
          </div>
          <div class="current_rides_item dropoff fl-l">
            <h3>Drop Off:</h3>
            <p><%= @dropoff_address.try(:address) %></p>
          </div>
        </div>
      </div>
      <div class="current_rides_map">
        <div id="map" class="map_holder"></div>    
      </div>
    </div>
  </div>
  <div class="col3 sidebar fl-r">
    <div class="grid_item gray_box">
      <div class="grid_item_headings clearfix">
        <h1>Schedule Rides</h1>
      </div>
      <hr>
        <%= render :partial => 'schedule_rides' %>
    </div>
    <div class="grid_item  all_current_rides gray_box">
      <div class="grid_item_headings clearfix">
        <h1>All Current Rides</h1>
      </div>
      <hr>
      <% i= 1 %>
      <% @all_current_rides.each do |all_rides|%>
        <div class="grid_item_content">
          <div class="all_current_rides_item">
            <p>
              <strong><%= current_rides_pickup_date(all_rides.try(:pickup_datetime))%> at <%= current_rides_pickup_time(all_rides.try(:pickup_time))%></strong>
            </p>
            <p>
              <%= @pickup_address.try(:address) %>
              <% if (i!=2) %>
                <% i=i+1 %>
                <span class="current_rides_highlight">Current Rides</span>
              <% else %>
                <a href="#" id ="view_current_ride">View Details</a>
              <% end %>
            </p>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $("#view_current_ride").click(function(){
    alert("murari");
      
      });
    });
  });
</script>
  

app/views/rides/_past_rides.html.erb
<% @rides.each do |ride|%>
  <div class="grid_item_content">
    <div class="clearfix">
      <h2 class="fl-l"><%= past_date(ride.try(:pickup_datetime)) %> Taxi Ride:</h2>
    </div>
    <div class="current_rides_item">
      <h3>Taxi Company:</h3>
      <p><%= get_taxi_info(ride.taxi_info_id).try(:taxi_company_name)%></p>
      <p><%= get_taxi_info(ride.taxi_info_id).try(:taxi_company_phone_no)%></p>
    </div>
    <div class="clearfix">
      <div class="current_rides_item pickup fl-l">
        <h3>Pickup:</h3>
        <p><%= ride.showpickup_address(ride.id) %></p>
        <p>Alexandria, VA 22314</p>
      </div>
      <div class="current_rides_item dropoff fl-l">
        <h3>Drop Off:</h3>
        <p><%= ride.showdropoff_address(ride.id) %></p>
        <p>Alexandria, VA 22314</p>
      </div>
    </div>
  </div>
<% end %>

app/views/rides/_past_rides_tab.html.erb
<div class="content grid my_rides clearfix">
  <div class="col3 col3_span fl-l">
    <div class="grid_item current_rides gray_box">
      <div class="grid_item_headings clearfix">
        <h1 class="fl-l">Past Rides</h1>
        <%= form_tag past_rides_path, :params => params, :remote => true, :method => "get" do %>
        <div class="fl-r">
          <ul class="form_wrap clearfix">
            <li class="no-mrg">
              <ul>
                <li class="fl-l no-mrg">From <%= text_field_tag :pickup_datetime, params[:pickup_datetime], :placeholder =>"Start Date", :id => "date_pick_up", :class =>"input_ico input_ico_date datepicker"%></li>
                <li class="fl-l no-mrg">&nbsp;to<%= text_field_tag :return_pickup_datetime, params[:return_pickup_datetime], :placeholder =>"End Date", :id => "return_date_pick_up", :class => "input_ico input_ico_date datepicker"%></li>
              </ul>
            </li>
          </ul>
        </div>
        <% end %>
      </div>
      
      <hr>
      <div class="content_wrap clearfix", id = "past_rides">
        <%= render :partial => 'past_rides' %>
      </div>
    </div>
    <div class="pagination fl-r clearfix">
    <div class="fl-l">
      <%= will_paginate @rides, :class=>"paging_full_numbers"%>
    </div>
  </div> 
    <script type="text/javascript">
      $(document).ready(function(){
        $("#date_pick_up, #return_date_pick_up").change(function(event){
          if( $("#date_pick_up").val() != "" && $("#return_date_pick_up").val() != "" ){
            $.ajax({
              url: "<%= past_rides_path %>",
              type: "GET",
              data: {'pickup_datetime': $("#date_pick_up").val() , 'return_pickup_datetime': $("#return_date_pick_up").val() },
              success: function(data){}
            });
          }
        });
      });
    </script>

  </div>
  <div class="col3 sidebar fl-r">
    <div class="grid_item gray_box">
      <div class="grid_item_headings clearfix">
        <h1>Schedule Rides</h1>
      </div>
      <hr>
      <%= render :partial => 'schedule_rides' %>

    </div>
    <div class="grid_item  all_current_rides gray_box">
      <div class="grid_item_headings clearfix">
        <h1>All Past Rides</h1>
      </div>
      <hr>
      <% @rides.each do |past_rides|%>
      <div class="grid_item_content">
        <div class="all_current_rides_item">
          <p>
            <strong><%= current_rides_pickup_date(past_rides.try(:pickup_datetime))%> at <%= current_rides_pickup_time(past_rides.try(:pickup_time))%></strong>
          </p>
          <p>
            <%= past_rides.showpickup_address(past_rides.id) %>
              <a href="#">View Details</a>
          </p>
        </div>
      </div>
      <%end%>
    </div>
  </div>
</div>
    

app/views/rides/_rides_main_tab.html.erb
<div class="content_wrap clearfix">
  <div class="content_heading">
    My Rides
  </div>
  <div class="content_nav tplshadow">
    <ul>
      <li class="first <%= get_rides_tab_status(params[:action], 'index') %>">
        <%= link_to rides_path do %>
          Current Rides<span class="content_nav_arrow"></span>
        <% end %>
      </li>
      <li class="<%= get_rides_tab_status(params[:action], 'past_rides') %>">
        <%= link_to past_rides_path do %>
          Past rides<span class="content_nav_arrow"></span>
        <% end %>
      </li>
      <li class="last <%= get_rides_tab_status(params[:action], 'cancelled_rides') %>">
        <%= link_to cancelled_rides_path do %>
          Cancelled Rides<span class="content_nav_arrow"></span>
        <% end %>
      </li>
    </ul>
  </div>
  <%= render :partial => get_rides_tabs_partial(params[:action])%>
</div>

app/views/rides/_schedule_rides.html.erb
<% @scheduled_rides.each do |scheduled_rides|%>  
  <div class="grid_item_content">
  <% if scheduled_rides %>
    <p>
      <strong><%= current_rides_pickup_date(scheduled_rides.try(:pickup_datetime))%> at <%= current_rides_pickup_time(scheduled_rides.try(:pickup_time))%></strong>
    </p>
    <p>
      <%= scheduled_rides.showpickup_address(scheduled_rides.id) %>
      <a href="#">View Details</a> 
    </p>
  <% else %>                     
    <strong>You have no upcoming rides</strong>
  <% end %>    
  </div>
<% end %> 

app/views/rides/cancelled_rides.html.erb
<%= render :partial => 'rides_main_tab' %>

app/views/rides/index.html.erb
<%= render :partial=> 'rides_main_tab'%>
<script>
handler = Gmaps.build('Google', { markers: { maxRandomDistance: null } });
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  markers = handler.addMarkers(<%=raw @hash1.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);
  handler.getMode('DRIVING');
  handler.direction_conf.display_panel(true);
});
</script>

app/views/rides/past_rides.html.erb
<%= render :partial => 'rides_main_tab' %>

app/views/rides/past_rides.js.erb
$("#past_rides").html("<%= escape_javascript(render(:partial => 'past_rides')) %>");