config/routes.rb
Taxidispatch::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations",
                                       :sessions => "sessions",
                                       :passwords => "passwords"} do

  end

  resource :user, only: [:show] do
    collection do
      get 'edit_password'
      patch 'update_password'
    end
  end

  resources :my_accounts
  resources :rides
  resources :bookings
  resources :vehicle_preferences
  resource :user, only: [:show] do
    collection do
      patch 'update_password'
      get 'edit_password'

    end
  end

  get "get_address" => 'bookings#get_address'
  get "show_new_booking_map" => 'bookings#show_new_booking_map'
  get "booking_history" => 'bookings#booking_history'
  get "past_rides" => 'rides#past_rides'
  get "cancelled_rides" => 'rides#cancelled_rides'

  get "home/index"
  get "home/help"
  get "home/email_us"
  post "home/nearest_texi"
  

   root 'home#index'

  

end

app/views/layouts/_masseges.html.erb
<% flash.each do |name, msg| %>
  <div id="flash" class="flash <%= name%>">
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#flash').remove();
  }, 5000);
 })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>New Booking - Chater Taxi</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link href='http://fonts.googleapis.com/css?family=Cuprum|Roboto:500,700' rel='stylesheet' type='text/css'>

    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "main", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "forms", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="wrap">
      <div class="header_topbar_wrap">
        <div class="header_topbar clearfix">
          <a href="/" class="header_logo fl-l">
              <span class="logo ir">Chater Taxi</span> 
              Taxi dispatch &amp; management
          </a>
          <div class="header_userinfo fl-r">
            <% if user_signed_in? %>
              <div>Welcome <%= current_user.first_name %>&nbsp;<%= current_user.last_name %> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></div> 
              <div>Canada<%= link_to "Change", edit_user_registration_path, :class => "modal_ajax", :title => "Edit Personal Information" %></div>
            <% else %>
              <%= link_to "Login", new_user_session_path, :class => "modal_ajax", :title => "Login" %> <%= link_to "Create Account", new_user_registration_path, :class => "modal_ajax", :title => "Create Account" %> 
            <% end %>                
          </div>
        </div>
      </div>

      <div class="header_menu_wrap">
        <div class="header_menu clearfix">
          <ul class="clearfix">
          <% if user_signed_in? %>
            <li><%= link_to "New Booking", new_booking_path%></li>
            <li><%= link_to "Booking History", booking_history_path%></li>
            <li><%= link_to "My Account", my_accounts_path %></li>
            <li><%= link_to "My Rides", rides_path %></li>
            <li><a href="#">Receipts</a></li>
            <li class="active"><a href="/home/help">Help</a></li>
            <li><a href="/home/email_us" class="modal_ajax" title="Email Us">Email Us</a></li>
          <% else %>
            <li><a href="/users/sign_in" class="modal_ajax">New Booking</a></li>
            <li><a href="/users/sign_in" class="modal_ajax">Booking History</a></li>
            <li><a href="/users/sign_in" class="modal_ajax">My Account</a></li>
            <li><a href="/users/sign_in" class="modal_ajax">My Rides</a></li>
            <li><a href="/users/sign_in" class="modal_ajax">Receipts</a></li>          
            <li class="active"><a href="/home/help">Help</a></li>
            <li><a href="/home/email_us" class="modal_ajax" title="Email Us">Email Us</a></li>
          <% end %> 
          </ul>
        </div>
      </div>

      <%= yield %>
      <%= yield :scripts %>
      <div class="footer_empty"></div>
    </div>
    <div class="footer_wrap">
      <div class="footer_bg"></div>
      <div class="footer clearfix">
        <div class="footer_menu fl-l">
          <ul>
            <li><a href="about.html">About Us</a></li>
            <li><a href="help.html">Help</a></li>
            <li><a href="privacy.html">Privacy Policy</a></li>
            <li><a href="#">Terms &amp; Conditions</a></li>
            <li><a href="#">Download App</a></li>
            <li><a href="contact.html">Contact Us</a></li>
          </ul>
        </div>
        <div class="copyright fl-r">
          Copyright 2013, Chater Taxi Inc. Canada
        </div>
      </div>
    </div>

    <%= javascript_include_tag "bottum_application", "data-turbolinks-track" => true %>
  </body>
</html>

app/views/layouts/user_account.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>New Booking - Chater Taxi</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "main", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "forms", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrap">
    <%= yield %>
  </div>
  <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
  </body>
  
</html>